/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package github._2k16daniel.drfclient;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
